version: 0.0
os: linux
files:
- source: /
  destination: /home/ubuntu/app

permissions:
- object: /
   pattern: "**"
   owner: ubuntu
   group: ubuntu

hooks:
    AfterInstall:
        - location: /bin/afterinstall.sh

artifacts:
  files:
    - app.js
    - package.json
    - appspec.yml
    - bin
    - config
    - docs
    - lib
    - migrations
    - public
    - scripts
    - scss
    - t
    - views
