version: 0.0
os: linux
files:
- source: /
  destination: /var/www/

permissions:
- object: /var/www
   pattern: "**"
   owner: ubuntu
   group: ubuntu

hooks:
    ApplicationStop:
        - location: /bin/stop.sh
    BeforeInstall:
        - location: /bin/beforeinstall.sh
    ApplicationStart:
        - location: /bin/start.sh

artifacts:
  files:
    - app.js
    - package.json
    - appspec.yml
    - buildspec.yml
    - .npmrc
    - codeclimate.yml
    - .gitingore
    - .travis.yml
    - bin
    - config
    - docs
    - lib
    - migrations
    - public
    - scripts
    - scss
    - t
    - views
    - .ebextensions
    - .git
    - templates
    