version: 0.0
os: linux
files:
- source: /
  destination: /home/ec2-user/app

permissions:
- object: /
   pattern: "**"
   owner: ec2-user
   group: ec2-user

hooks:
    Install:
        - location: /bin/afterinstall.sh

artifacts:
  files:
    - app.js
    - package.json
    - appspec.yml
    - buildspec.yml
    - bin/*
    - config/*
    - docs/*
    - lib/*
    - migrations/*
    - public/*
    - scripts/*
    - scss/*
    - t/*
    - views/*
