version: 0.0
os: linux
files:
- source: /
  destination: /var/www/

permissions:
- object: /
   pattern: "**"
   owner: ec2-user
   group: ec2-user

hooks:
    ApplicationStop:
        - location: /bin/stop.sh
    BeforeInstallation:
        - localtion: /bin/beforeinstall.sh
    ApplicationStart:
        - location: /bin/start.sh
    validateService:
        - location /bin/validate.sh
    
        

artifacts:
  files:
    - app.js
    - package.json
    - appspec.yml
    - buildspec.yml
    - bin/*
    - config/*
    - docs/*
    - lib/*
    - migrations/*
    - public/*
    - scripts/*
    - scss/*
    - t/*
    - views/*
