---
- hosts: ec2-app-server
  become: yes
  name: Install NodeJS 
  tasks:
  roles:
    - geerlingguy.nodejs


  name: Print NodeJS version
  shell: node --version
  args:
   executable: /bin/bash
  register: node_version

  debug: msg="{{ node_version.stdout_lines }}"

  name: Print NPM version
  command: npm --version
  register: npm_version

  debug: msg="{{ npm_version.stout_lines }}"



